version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - gosec
    - misspell
    - unconvert
    - goconst
    - gocyclo
    - funlen
    - gocritic
    - godot
    - err113
    - nolintlint
    - rowserrcheck
    - sqlclosecheck
    - unparam
    - nilerr
    - nilnil
    - prealloc
    - predeclared
    - gosmopolitan
    - tagliatelle
    - varnamelen
    - wrapcheck