run:
  timeout: 5m
  go: '1.21'
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gosec
    - misspell
    - unconvert
    - goconst
    - gocyclo
    - funlen
    - gocritic
    - godot
    - goerr113
    - gofumpt
    - nolintlint
    - rowserrcheck
    - sqlclosecheck
    - unparam
    - nilerr
    - nilnil
    - prealloc
    - predeclared

linters-settings:
  goimports:
    local-prefixes: github.com/FreePeak/commitgen

  gocyclo:
    min-complexity: 15

  goconst:
    min-len: 3
    min-occurrences: 3

  funlen:
    lines: 100
    statements: 50

  gofumpt:
    extra-rules: true

  nolintlint:
    require-explanation: true
    require-specific: true

issues:
  exclude-rules:
    # Exclude known linter issues
    - path: _test.go
      linters:
        - gosec
        - funlen
        - goconst

    # Exclude some errcheck issues
    - linters:
        - errcheck
      text: "Error return value of .((os.)?std(out|err)..*|.*Close|.*Flush|os.Remove(All)?|.*printf?|os.(Un)?Setenv). is not checked"

    # Exclude main function
    - path: main.go
      linters:
        - funlen

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0